### ISSUE TITLE
Is the metric version missing SidePanel_L ?

### ISSUE THREAD

**Issue by joachimurbain** [Sillybutts/SLAB#4]
Hey,
Is the metric version missing the file Metric_SidePanel_L.stl or is the base file  ( SidePanel_L.stl ) compatible ?
Was wondering as there is a Metric_SidePanel_R.stl.

Thank you !

**Comment by Sillybutts** [comment]
Correct, there is **no** metric sidepanel_L. Use the standard SLAB SidePanel_L. 

The right one needed changing because the metric pins I used have larger heads than the imperial version (standard SLAB). So, I widened the pin clearance for the head on the Right side panel. The left side panel doesn't have the head go through it, so this change wasn't needed on the left.
